[package]
name = "wei-env"
version = "0.1.0"
edition = "2021"
description = "wei env"
documentation = "https://github.com/zuiyue-com/wei-env"
homepage = "https://github.com/zuiyue-com/wei-env"
license = "MIT OR Apache-2.0"

[dependencies]
